### ISSUE TITLE
Possible to push FocusGained events to output.events?

### ISSUE THREAD

**Issue by ndarilek** [idanarye/bevy-egui-kbgp#1]
Hey, thanks so much for this crate!

I'm making blind-accessible games for which the keyboard/gamepad are very important. Currently I use egui, but tab/shift-tab aren't ideal and creating something better has been on the todo list for a while.

This crate almost works for me, but I'm using `output.events` and a Bevy system as kind of a kludgy screen reader. You can get an idea of what I'm doing [here](https://github.com/ndarilek/bevy_egui_a11y).

When you move focus to a new widget, would it be possible to push an event so this crate could be compatible with my bevy_egui_a11y demo? It doesn't seem too difficult, and if you don't have time but can point me to where and how I might do this myself then I'm happy to take a crack at it. You can see an example of how egui does this [here](https://github.com/emilk/egui/blob/master/egui/src/response.rs#L472). I guess the biggest challenge will be whether or not you've got enough info to create the focus events from within the plugin, though at least you're *only* dealing with focus and not other event types. :) Also wondering if it may be possible for the decorators to augment widgets with at least their type, name, and value if necessary so the plugin can create the necessary events. Those should be enough for at least basic versions of `FocusGained`.

Thanks again.

**Comment by idanarye** [comment]
Please try with the `fix-focus-event-emission` and see if it works well for you.

**Comment by ndarilek** [comment]
Unfortunately it seems to make things worse. :(


I just pushed a kbgp branch to the above demo. Unless I'm doing 
something wrong, this branch doesn't even present events when 
tabbing/shift-tabbing anymore.


Thanks for looking into this so quickly!

**Comment by idanarye** [comment]
I downloaded and built it, and on some runs it would indeed not do anything on focus events, but on other runs it'd work fine for both tab and arrow navigation.

This usually means that the order of systems matter.

In this case, when I changed your `screen_reader` system run before egui processes output:
```rust
.add_system_to_stage(CoreStage::PostUpdate, screen_reader.system().before(bevy_egui::EguiSystem::ProcessOutput))
```
it works consistently. When I change it to run `after` instead, it doesn't work - also consistently.

I think a system labeled with `bevy_egui::ProcessOutput` that runs during the post update stage wipes out the output events.

**Comment by ndarilek** [comment]
Oh, you're absolutely right. I'd made that change in my game but forgot 
that I hadn't made it in the concept demo. Sorry about that.


It does seem to work consistently now. Thanks! I'll integrate it into my 
game for broader testing as soon as it's released.


Thanks again for making this. It's always nice when I can strike 
something major like this from the todo list.

**Comment by ndarilek** [comment]
Oh, one minor thing I noticed, not sure if it's something you can fix. I don't get an event for `.kbgp_initial_focus()` on my "Start" button. Other events now work consistently.

**Comment by idanarye** [comment]
Try now (same branch)

**Comment by ndarilek** [comment]
Yup, works now. Thanks!
