### ISSUE TITLE
Can't get focus working on state transitions

### ISSUE THREAD

**Issue by ndarilek** [idanarye/bevy-egui-kbgp#3]
I've ported [bevy_egui_a11y](https://github.com/ndarilek/bevy_egui_a11y) to this library. One issue that I'm hitting in my game, and can duplicate here, is that focus doesn't seem to work on state transitions. It's possible that I'm doing these wrong, and I know Bevy's state system has some rough edges. Here's what I'm doing, and what I'm observing:

```
        if ui.button("Submenu").kbgp_navigation().clicked() {
            ui.kbgp_clear_input();
            state.push(AppState::SubMenu).unwrap();
        }
...
// in my submenu system, running on_update of `Submenu` state
        if ui.button("Back").kbgp_navigation().clicked() {
            ui.kbgp_clear_input();
            state.pop().unwrap();
        }
```

* The menus successfully open and transition.
* All menus are keyboard-navigable with arrows.
* When the submenu opens, focus isn't moved to the initial focus control. I'm blind, so I can't tell if the mouse pointer does something here that my hacky screen reader system can't pick up on.
* When the back button is clicked, focus doesn't return to the Submenu button that triggered the state transition.

Not sure how and to what extent any of this can be fixed, but thought I'd report it anyway. It might also be a system ordering issue--not sure if I need to run my systems before any in the plugin take control.

Thanks again.

**Comment by idanarye** [comment]
This is actually a hard problem I've been trying to solve for a while now. But I can see why it is worse in your case...

One thing to consider though - the current behavior is that when the state changes if there is another widget in the same place where the focus used to be the focus will transfer to it (apparently they are getting the same ID?). This is often a welcome behavior - for example in the demo example it makes sense for the focus to be on the same button.

I wonder if it makes sense to keep this behavior. Or maybe this should be a flag?

**Comment by ndarilek** [comment]
Hmm, I'm not entirely clear on what you're saying. Are you saying that 
focus doesn't move to the initial focus in some situations? Reading that 
method's description, I see that it refers to UI creation. I guess 
pushing a new state doesn't qualify as UI creation? Or am I 
misunderstanding what you're saying?

I feel like for keyboard-focused navigation, you probably don't want 
focus behaving based on mouse position. If I'm arrowing through menu 
UIs, my expectation is that I'd always land in the same place when 
clicking through to a submenu. I think that's how most console games I'm 
familiar with work.

If that's what you're suggesting making configurable, I'm all for it. :) 
Hope I'm clear on what the issue here is. It's hard for me to wrap my 
head around how egui behaves because I can't match the mouse position 
with how the UI is drawn. I'm having to speculate wildly on a lot of 
what's going on, which is part of why I haven't written keyboard support 
already. :)

**Comment by idanarye** [comment]
I'm thinking about introducing "focus labels", and when you change the state you can set a focus label (initial focus will have a special label). If you don't set the label you get the current behavior, but you can set it to specify exactly which widget to go to.

Alternatively, maybe I should make it so that you **have** to set the label, and the block the current behavior entirely?

**Comment by ndarilek** [comment]
I'm not immediately sure if or when the current behavior would make 
sense, so I'll withhold judgment on whether it should stay. But I think 
the focus labels sound like a good direction.
